image: node:16.13.1-alpine

# if the image is specified at the top it'll be by default used in each stage
# wherein is no image

stages:
  - build
  - test
  - deploy

build website:
  stage: build
  script:
    - npm install --silent
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths: 
      - ./public

test artifact:
  stage: test
  image: alpine
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm install --silent
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - apk --no-cache add curl
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"

# default Gatsby ports: 9000 in serve, 8000 in develop
# gatsby serve & - an ampersand runs the process in the background
# | tac | tac | - is a workaround for an error: (23) Failed writing body https://stackoverflow.com/a/28879552/1521866

deploy to surge:
  stage: deploy
  script:
    - npm install --global surge
    - surge --project ./public --domain carrotcabbage.surge.sh